syntax = "proto3";
package payment;

service PaymentService {
  rpc InitiatePayment (InitiatePaymentRequest) returns (InitiatePaymentResponse);
  rpc ConfirmPayment  (ConfirmPaymentRequest)  returns (ConfirmPaymentResponse);
}

message InitiatePaymentRequest {
  string client_id                = 9;
  double amount                   = 1;
  string merchant_order_reference = 2;
  string success_url              = 3;
  string fail_url                 = 4;
  string cancel_url               = 5;
  string notification_url         = 6;
  string currency                 = 7;
  string description              = 8;
}

message InitiatePaymentResponse {
  bool   success          = 1;
  string message          = 2;
  string payment_form_url = 3;
  string rai_order_id     = 4;
}

message ConfirmPaymentRequest {
  string rai_order_id = 1;
  string client_id    = 2;
}

message ConfirmPaymentResponse {
  bool   success          = 1;
  string message          = 2;
  string rai_order_status = 3;
}

