syntax = "proto3";
package user;

service UserService {
  rpc ListUsers    (ListUsersRequest)    returns (ListUsersResponse);
  rpc RegisterUser (RegisterUserRequest) returns (SimpleResponse);
  rpc UpdateUser   (UpdateUserRequest)   returns (SimpleResponse);
  rpc DeleteUser   (DeleteUserRequest)   returns (SimpleResponse);
  rpc ListClients  (ListClientsRequest)  returns (ListClientsResponse);
  rpc UpdateClient (UpdateClientRequest) returns (SimpleResponse);
  rpc DeleteClient (DeleteClientRequest) returns (SimpleResponse);
  rpc SetCurrency      (SetCurrencyRequest)      returns (SimpleResponse);
  rpc SetBalance       (SetBalanceRequest)       returns (SimpleResponse);
  rpc AddBalance       (AddBalanceRequest)       returns (AddBalanceResponse);
  rpc GetClientBalance (GetClientBalanceRequest) returns (GetClientBalanceResponse);
}

message ListUsersRequest {}

message User {
  string id         = 1;
  string email      = 2;
  string name       = 3;
  string role       = 4;
  int64  created_at = 5;
}

message ListUsersResponse {
  repeated User users = 1;
}

message RegisterUserRequest {
  string email      = 1;
  string password   = 2;
  string name       = 3;
  string role       = 4;
  string created_by = 5;
}

message SimpleResponse {
  bool   success = 1;
  string message = 2;
}

message UpdateUserRequest {
  string id         = 1;
  string email      = 2;
  string name       = 3;
  string role       = 4;
  string password   = 5;
  string updated_by = 6;
}

message DeleteUserRequest {
  string id         = 1;
  string deleted_by = 2;
}

message ListClientsRequest {}

message ClientEntry {
  string id         = 1;
  string email      = 2;
  string name       = 3;
  int64  created_at = 4;
  string account_id = 5;
  string currency   = 6;
  double balance    = 7;
}

message ListClientsResponse {
  repeated ClientEntry clients = 1;
}

message UpdateClientRequest {
  string id         = 1;
  string email      = 2;
  string name       = 3;
  string password   = 4;
  string updated_by = 5;
}

message DeleteClientRequest {
  string id         = 1;
  string deleted_by = 2;
}

message SetCurrencyRequest {
  string client_id = 1;
  string currency  = 2;
}

message SetBalanceRequest {
  string client_id = 1;
  double balance   = 2;
}

message AddBalanceRequest {
  string client_id = 1;
  double amount    = 2;
}

message AddBalanceResponse {
  bool   success = 1;
  string message = 2;
  double balance = 3;
}

message GetClientBalanceRequest {
  string client_id = 1;
}

message GetClientBalanceResponse {
  double balance  = 1;
  string currency = 2;
}
